//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DVDLibraryService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DVD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DVD()
        {
            this.Notes = new HashSet<Note>();
        }
    
        public int DVDID { get; set; }
        public string Title { get; set; }
        public string Director { get; set; }
        public int RatingID { get; set; }
        public int realeaseYear { get; set; }
    
        public virtual Rating Rating { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Note> Notes { get; set; }
    }
}
